config/routes.rb
Selfstarter::Application.routes.draw do
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions"}
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'
  # namespace :admin do
  #   resources :order
  # end

  
  root to: "preorder#index"
  match '/preorder'               => 'preorder#index', :via => [:get,:post]
  # get 'preorder/checkout'
  get '/preorder/checkout_amount'
  # match '/preorder/share/:uuid'   => 'preorder#share', :via => :get
  # match '/preorder/ipn'           => 'preorder#ipn', :via => :post
  # match '/preorder/prefill'       => 'preorder#prefill', :via => [:get,:post]
  # match '/preorder/postfill'      => 'preorder#postfill', :via => [:get,:post]
  match '/preorder/stripe_checkout'      => 'preorder#stripe_checkout', :via => [:get,:post]
  match '/preorder/checkout_amount'      => 'preorder#checkout_amount', :via => [:get,:post]
  match '/news'    => 'preorder#news', :via => :get
  match '/presskit'    => 'preorder#presskit', :via => :get
  match '/comments'    => 'preorder#comments', :via => :get
  match '/contact'    => 'preorder#contact', :via => :get
  # match '/confirm'    => 'order#confirm', :via => [:get,:post]
  post 'order/confirm/:id' => 'order#confirm'
end


  # mount RailsAdmin::Engine => '/backend', :as => 'rails_admin'
  # mount Rich::Engine => '/rich', :as => 'ric

app/controllers/preorder_controller.rb
class PreorderController < ApplicationController
  include ActionView::Helpers::DateHelper
  # skip_before_action :verify_authenticity_token, :only => :ipn
  before_action :authenticate_user!, :only => :stripe_checkout
  def index
    if params[:data] == "checked"
      UserMailer.confirm_order(User.find_by_id(params[:id].to_i).email).deliver
    end
  end

  # def checkout
  # end

  # def prefill
  #   @user = User.find_or_create_by(:email => params[:email])

  #   if Settings.use_payment_options
  #     payment_option_id = params['payment_option']
  #     raise Exception.new("No payment option was selected") if payment_option_id.nil?
  #     payment_option = PaymentOption.find(payment_option_id)
  #     price = payment_option.amount
  #   else
  #     price = Settings.price
  #   end

  #   @order = Order.prefill!(:name => Settings.product_name, :price => price, :user_id => @user.id, :payment_option => payment_option)

  #   # This is where all the magic happens. We create a multi-use token with Amazon, letting us charge the user's Amazon account
  #   # Then, if they confirm the payment, Amazon POSTs us their shipping details and phone number
  #   # From there, we save it, and voila, we got ourselves a preorder!
  #   port = Rails.env.production? ? "" : ":3000"
  #   callback_url = "#{request.scheme}://#{request.host}#{port}/preorder/postfill"
  #   redirect_to AmazonFlexPay.multi_use_pipeline(@order.uuid, callback_url,
  #                                                :transaction_amount => price,
  #                                                :global_amount_limit => price + Settings.charge_limit,
  #                                                :collect_shipping_address => "True",
  #                                                :payment_reason => Settings.payment_description)
  # end

  # def postfill
  #   unless params[:callerReference].blank?
  #     @order = Order.postfill!(params)
  #   end
  #   # "A" means the user cancelled the preorder before clicking "Confirm" on Amazon Payments.
  #   if params['status'] != 'A' && @order.present?
  #     redirect_to :action => :share, :uuid => @order.uuid
  #   else
  #     redirect_to root_url
  #   end
  # end

  # def share
  #   @order = Order.find_by(:uuid => params[:uuid])
  # end

  # def ipn
  # end

  def stripe_checkout

    begin
    # Stripe.api_key = Strip.find(1).api_key
    Stripe.api_key = "sk_test_rhYccwn5XNuhTA52oEJayjy2"
    customer = Stripe::Customer.create(
      :email => 'example@stripe.com',
      :card  => params[:stripeToken]
    )
 
    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => params[:amount].to_i,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

    @data = JSON.parse charge.to_s
    @address = Order.create(:name => params[:name], :phone => params[:phone], :hno => params[:hno], :city => params[:city], :state => params[:state], :zip => params[:zip], :country => params[:country], :transaction_id => @data["balance_transaction"], :user_id => current_user.id, :price => params[:amount], :quantity => params[:quantity], :product => params[:title], :est_delivery=> params[:deliver], :international_shipping=> params[:ship] )
    
    
    # @payment = PaymentOption.create(:amount => params[:amount].to_f, :amount_display => params[:amount].to_f, :shipping_desc => params[:ship], :delivery_desc => params[:deliver])
#     card_token = Stripe::Token.create( :card => { :name => params[:name_on_card], :number => params[:card_number], :exp_month => params[:exp_month], :exp_year => params[:exp_year], :cvc => params[:card_id] })
#         binding.pry
#     customer_params = {:card => card_token[:id], :email => params[:email]}
#     stripe_customer = Stripe::Customer.create(customer_params)
    # @payment.save
    @address.save
    UserMailer.confirm_payment(@data["source"]["name"], params[:title], params[:quantity].to_i, params[:amount].to_f, @data["card"]["last4"].to_i, @data["balance_transaction"]).deliver
    UserMailer.order_rcvd(User.find_by_admin(true).email, params[:title], params[:quantity].to_i, params[:amount].to_f, @data["card"]["last4"].to_i, @data["balance_transaction"]).deliver
    rescue Stripe::CardError => e
      flash[:error] = e.message
    end
  end

  def checkout_amount

  end



end


     

app/helpers/preorder_helper.rb
module PreorderHelper
  def like_button(width = 70, show_faces = false)
    raw "<div class=\"fb-like\" data-send=\"false\" data-width=\"#{width}\" data-layout=\"box_count\" data-show-faces=\"true\"></div>"
  end
  def pin_it_button
    image_url = URI.encode("#{request.scheme}://#{request.host}#{image_path(Settings.product_image_path)}")
    raw "<a href='http://pinterest.com/pin/create/button/?url=#{encoded_root_url}&media=#{image_url}' class='pin-it-button' count-layout='vertical'><img border='0' src='//assets.pinterest.com/images/PinExt.png' title='Pin It' /></a>"
  end
  def tweet_button
    tweet_text = "I'm #{Settings.primary_stat_verb} number #{number_with_delimiter Order.backers, :delimiter => ","} #{Settings.tweet_text}!"
    raw "<a href='https://twitter.com/share?url=/' id='tweet_button' class='twitter-share-button twitter-button' data-url=#{request.scheme}//#{request.host}' data-via='#{Settings.product_name}' data-lang='en' data-count='vertical' data-text=\"#{tweet_text}\">Tweet</a>"
  end

  def video_url
    "#{Settings.video_embed_url}?" + case Settings.video_embed_url
    when /vimeo/
      'title=0&byline=0&portrait=0&autoplay=0'
    when /youtube/
      'autohide=1&showinfo=0&rel=0&autoplay=0'
    else
      ''
    end
  end

  def encoded_root_url
    raw URI.encode "#{request.scheme}://#{request.host}/preorder"
  end

  def sold_out(payment_option)
    payment_option.limit > -1 and order_count(payment_option) >= payment_option.limit
  end

  def order_count(payment_option)
    Order.where(payment_option_id: payment_option).count(:token) # count of orders that have a token from amazon and are for this payment option
  end
end

app/views/preorder/_copyright.html.erb
<p class="pull-right">© 2015 - Copyright Gwen & Tiana</p>

app/views/preorder/_foot.html.erb
<div id="second_call_to_action">
      <div class="container">
      <div></div>
      <div class="center">
        <a href="/preorder/checkout_amount" class="blue_button" id="secondary_cta">
          Contribute
        </a>
        
      </div>
       </div>
    </div>

    <div id="faq">
      <div class="container clearfix">
      <div class="center">
        <h3>Frequently Asked Questions</h3>
      </div>
      <ul>
        <li class=''>
          <details class=''>
            <summary class=''>When will I be charged?</summary>
            <p><p>Your Credit Card is charged immediately when you pledge even if the project hasn't reach its goal yet. If the project has already reached its goal (or is a pre-order with no goal) the Credit Card is also charged immediately. </p></p>
          </details>
        </li>
        <li class=''>
          <details class=''>
            <summary class=''>Why was my payment declined?</summary>
            <p><p>Assuming you have the necessary funds it was likely declined by your card issuer due to their fraud/security policies. You’ll have to contact them directly and ask them to authorize for the payment to go through. Keep them on the phone while you try the payment again to make sure it goes through – sometimes they don’t unlock everything properly the first time.</p></p>
          </details>
        </li>
      </ul>
      <ul class="col2">
        <li class=''>
          <details class=''>
            <summary class=''>Is this a secure transaction?</summary>
            <p><p>Definitely. Your payment information is passed through a secure connection to our Website. Credit card information is never stored on our servers.</p></p>
          </details>
        </li>
        <li class=''>
          <details class=''>
            <summary class=''>How long will it be before I get my stuff?</summary>
            <p><p>This will depend on the artist. They will give you some updates during the project process. We will make sure that what you have pledged for reaches you as soon as possible.</p></p>
          </details>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/preorder/_footer.html.erb
<div class="footer">
  <div class="wrapper clearfix">
    <%= render 'preorder/copyright' %>
  </div>
</div>
<%= render 'preorder/google_analytics' %>

app/views/preorder/_google_analytics.html.erb
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '<%= Settings.google_id %>']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

app/views/preorder/_nav_stab.html.erb
    <div class="container">
      <ul class="nav nav-tabs">
        <li class="one"><a href="/">Description</a></li>
        <li class="two"><a href="/news">News</a></li>
        <li class="three"><a href="/contact">Contact</a></li>
        <li class="four"><a href="/presskit">Press Kit</a></li>
        <li class="five"><a href="/comments">Comments</a></li>
        <div style="float:right; padding-right:14px; padding-top:10px;">
            <% if user_signed_in? %>
              Logged in as <strong><%= current_user.email %></strong>.
              <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
              <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
              <% else %>
              <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
              <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
            <% end %>
        </div>
      </ul> 
    </div>  
       

app/views/preorder/_nav_tabs.html.erb
<ul class="nav nav-tabs">
    <li class="one"><a href="/">Description</a></li>
    <li class="two"><a href="/news">News</a></li>
    <li class="three"><a href="/contact">Contact</a></li>
    <li class="four"><a href="presskit">Press Kit</a></li>
    <li class="five"><a href="/comments">Comments</a></li>
</ul>

app/views/preorder/_reward_sidebar.html.erb
        <div class="rewards_sidebar">
          <h3>Rewards</h3>
          <ul>
            <% Service.all(:order => 'amount').each do |s| %> 
              <li class="rewards_click">
               <a href="/preorder/checkout_amount?reward=<%=s.id%>">
                  <p class="price">$<%= s.amount %></p>
                  <p class="title"><%= s.Product %></p>
                  <p class="image"><%= image_tag s.image.url(:thumb) %></p>
                  <p class="description"><%= s.Description %></p>
                  <div class="reward-delivery">
                    <p class="delivery">Estimated Delivery: <%= s.Est_Delivery %></p>
                    <p class="shipping">International shipping - <%= s.international_shipping %></p>
                  </div>
                </a> 
              </li>
            <% end %> 
          </ul>
        </div>

app/views/preorder/checkout_amount.html.erb
  <head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
     <script type="text/javascript">window.NREUM||(NREUM={});NREUM.info={"beacon":"bam.nr-data.net","errorBeacon":"bam.nr-data.net","licenseKey":"7dbfbf9e37","applicationID":"3521223","transactionName":"c1cIFktXXVldQxxSV11IBwteVkIaW1lWUl1fTRI9WFVeQFZF","queueTime":3,"applicationTime":133,"agentToken":null,"agent":"js-agent.newrelic.com/nr-632.min.js"}</script>

      <script type="text/javascript">
        var _sift = _sift || [];
       _sift.push(['_setAccount', '08a932d91b']);
       _sift.push(['_setUserId', '']);
       _sift.push(['_setSessionId', 'f9b149cc7eb5a8c1694501534d6b280d']);
       _sift.push(['_trackPageview']);
       (function() {
          function ls() {
          var e = document.createElement('script');
          e.type = 'text/javascript';
          e.async = true;
          e.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'cdn.siftscience.com/s.js';
          var s = document.getElementsByTagName('script')[0];
          s.parentNode.insertBefore(e, s);
        } 
       if (window.attachEvent) {
         window.attachEvent('onload', ls);
       } 
       else {
         window.addEventListener('load', ls, false);
       }
       })();
      </script>
  </head>

  <!--[if lt IE 9 ]><body class="lt-ie9"><![endif]-->
  <!--[if (gt IE 9)|!(IE)]><!--> <body><!--<![endif]-->
    <div id="main">      
        <%= render 'preorder/nav_stab' %>
      <div id="checkout">
        <div class="container"></div>
          <div class="container content_box clearfix">
            <div class="main_content">
              <h3><a href="/gwen-tiana-the-debut-album">Gwen &amp; Tiana - The debut album</a></h3>
                <div class="well checkout_block">
                  <!-- <form accept-charset="UTF-8" action="/gwen-tiana-the-debut-album/checkout/payment" method="GET" id="amount_form"> --> 
                  <%= form_tag preorder_stripe_checkout_path, :id => "amount_form" do %>  
                    <div class="amount_section">
                      <h4 class="amount_header">Your contribution amount: </h4>
                      <div class="amount_input" style="position:relative">
                        <input id="amount" type="text" name="amount" value="" data-price="1.00" />
                        <span style="position:absolute">$</span>
                        <i class="icon icon-info-sign show_tooltip minimum" data-placement="right" data-title="Minimum is $1.00"></i>
                      </div>
                    </div>
                    <div id="reward_select">
                      <h4>Select your reward:</h4>
                      <ul >
                        <% if params[:reward].present? %>
                          <li class="reward_option active  clearfix selected" data-id=<%= params[:reward] %> data-price= <%= Service.find_by_id(params[:reward]).amount.to_s %> data-num-available="10000">
                             <input class="reward_input" type="radio" name="reward" id= "rad" value=<%= params[:reward] %>>
                              <label class="price">$<%= Service.find_by_id(params[:reward]).amount %></label>
                              <div class="reward_description">
                                <p class="title"><%= Service.find_by_id(params[:reward]).Product %></p>
                                <p class="description"><%= Service.find_by_id(params[:reward]).Description %></p>
                                <p class="delivery">Estimated Delivery: <%= Service.find_by_id(params[:reward]).Est_Delivery %></p>
                              </div>
                                <%= hidden_field_tag "title", Service.find_by_id(params[:reward].to_i).Product %>
                                <%= hidden_field_tag "ship", Service.find_by_id(params[:reward]).international_shipping  %>
                                <%= hidden_field_tag "deliver", Service.find_by_id(params[:reward]).Est_Delivery  %>
                              <a class="reward_edit" href="#" style="display:none">edit</a>
                              <script type="text/javascript">$("#rad").prop ("checked", true);</script>
                          </li>
                        <% else %>
                          <li class="reward_option active clearfix" data-id="0" data-price="1.00">
                            <input class="reward_input" type="radio" name="reward" value="0">
                            <label class="price"></label>
                          <a class="reward_edit" href="#" style="display:none">edit</a>
                        </li>
                          <% Service.all.each do |s| %> 
                           <li class="reward_option active  clearfix" data-id=<%= s.id %> data-price=<%= s.amount.to_s%> data-num-available="10000">
                             <input class="reward_input" type="radio" name="reward" id= "rad" value=<%= s.id %> >
                             <label class="price">$<%= s.amount %></label>
                             <div class="reward_description">
                              <p class="title"><%= s.Product %></p>
                              <p class="description"><%= s.Description %></p>
                              <p class="delivery">Estimated Delivery: <%= s.Est_Delivery %></p>
                             </div>
                                <%= hidden_field_tag "title", Service.find_by_id(s.id).Product %>
                                <%= hidden_field_tag "ship", Service.find_by_id(s.id).international_shipping  %>
                                <%= hidden_field_tag "deliver", Service.find_by_id(s.id).Est_Delivery  %>
                             <a class="reward_edit" href="#" style="display:none">edit</a>
                           </li>
                          <% end %>   
                        <% end %>  
                      </ul>
                    </div>

                    <div style="margin-top:25px;">
                      <label for="reward-quantity" style="display: inline-block; margin-right: 5px;">Qty: </label>
                      <select name="quantity" style="width:60px; margin-right:18px;" id="reward-quantity" disabled>
                        <option value="1" selected >01</option>
                        <option value="2"  >02</option>
                        <option value="3"  >03</option>
                        <option value="4"  >04</option>
                        <option value="5"  >05</option>
                        <option value="6"  >06</option>
                        <option value="7"  >07</option>
                        <option value="8"  >08</option>
                        <option value="9"  >09</option>
                        <option value="10"  >10</option>
                      </select>
                      <span class="reward-total">Reward total: <strong class="subtotal">$0.00</strong></span>
                      <%# if user_signed_in? %>
                      <%#= link_to "Please add address details", address_path, :id => "button"%>
                    <%# else %>  
                      <%#= link_to "Please add address details", new_user_session_path, :id => "button"%>
                    <%# end %>
                      <!-- <button type="submit" class="btn btn-primary pull-right" id="continue_to_checkout" style="margin-top:0;">Continue to checkout</button -->
                    </div>
                    <br/>
                      <% if user_signed_in? %>
                      <h4>Address Details:</h4>
                      <p>
                         Name:<br />
                         <%= text_field_tag "name" %>
                      </p>

                      <p>
                         Phone:<br />
                         <%= text_field_tag "phone" %>
                      </p>

                      <p>
                         House Number:<br />
                         <%= text_field_tag "hno" %>
                      </p>

                      <p>
                         City:<br />
                         <%= text_field_tag "city" %>
                      </p>

                      <p>
                         State:<br />
                         <%= text_field_tag "state" %>
                      </p>

                      <p>
                         Zip:<br />
                         <%= text_field_tag "zip" %>
                      </p>
 
                      <p>
                         Country:<br />
                         <%= text_field_tag "country" %>
                      </p>
                      <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                        data-key="pk_test_rKiVOdu7iWsJtIkJkbrrA0Nl"
                        data-description="A month's subscription"
                        data-label="Payment">
                      </script>
                    <% else %>
                        <button id="myButton" style="background-image: linear-gradient(#7dc5ee,#008cdd 85%,#30a2e4);height: 30px;">Payment</button>

                        <script type="text/javascript">
                          document.getElementById("myButton").onclick = function () {
                          location.href = "/users/sign_in";
                          };
                        </script>                       
                    <!--      </form> -->
                    <% end %>
                  <% end %>
                </div>
            </div>

            <div class="sidebar">
              <div class="custom_content">
                <p style="text-align: justify;"><img alt="" src="https://s3.amazonaws.com/crowdtiltopen/CrowdtiltOpen/uploads/ckeditor/pictures/data/000/005/486/content.png" style="width: 150px; margin-top: 5px; margin-bottom: 5px; height: 42px;"><br>
                <span style="font-size:12px;">Vous êtes titulaires d’une carte Postifinance et vous souhaitez contribuer à notre projet. C’est très simple. Faites nous parvenir un virement bancaire sur le compte associatif de "Gwen &amp; Tiana » en précisant en objet, quel Item vous avez choisi.</span><br>
                <span style="font-size:12px;">Votre contribution sera enregistrée sur le site dès réception de votre virement et vous recevrez un e-mail de confirmation. Notez que vous pouvez également nous faire un don si vous souhaitez nous soutenir sans contre-partie. Nous vous remercions d’avance pour votre soutien. </span></p>
                <p> </p>
              </div>
            </div>
          </div>
        </div>
      </div>
  </body>

app/views/preorder/comments.html.erb
<head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
        <script type="text/javascript">window.NREUM||(NREUM={});NREUM.info={"beacon":"bam.nr-data.net","errorBeacon":"bam.nr-data.net","licenseKey":"7dbfbf9e37","applicationID":"3521223","transactionName":"c1cIFktXXVldQxxSV11IBwteVkIaUF5eVA==","queueTime":0,"applicationTime":395,"agentToken":null,"agent":"js-agent.newrelic.com/nr-632.min.js"}</script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

    <!--[if lt IE 9 ]><body class="lt-ie9"><![endif]-->
    <!--[if (gt IE 9)|!(IE)]><!--> <body><!--<![endif]-->

    <div id="fb-root"></div>
      <script>
        window.fbAsyncInit = function() {
        FB.init({
        appId      : '331145500360318',
        status     : true,
        xfbml      : true
        });
        };

        // Load the SDK asynchronously
        (function(d, s, id){
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) {return;}
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/en_US/all.js";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
      </script>

      <script>
        !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
      </script>
    </div>
    <div id="main"> 
     <div id="checkout">
     <%= render 'preorder/nav_stab' %>
      <div id="campaign">
    <div id="campaign_body">
      <div class="container clearfix">
        <div class="main_content narrow">
            <div class="tab-content">
              <div class="fb-comments" data-href="http://localhost/index" data-numposts="5" data-colorscheme="light"></div>
            </div>                  
        </div>
        <%= render 'preorder/reward_sidebar' %>
      </div>
    </div>

    <%= render 'preorder/foot' %>

  <div class="hide"><a href="https://gwentiana.tilt.com/gwen-tiana-the-debut-album#disqus_thread" data-disqus-identifier="gwen-tiana-the-debut-album" id="parse">0</a></div>
  <script type="text/javascript">
    var disqus_shortname = 'gwentiana';

    (function () {
    var s = document.createElement('script'); s.async = true;
    s.type = 'text/javascript';
    s.src = '//' + disqus_shortname + '.disqus.com/count.js';
    (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());
  </script>
  <script>
    window.onload = function(){

      var parse = document.getElementById('parse');
      var count = document.getElementById('count');

      count.innerHTML=parseInt(parse.innerHTML,10);
    };
  </script>
</div>
    </div>

    <script type="text/javascript" src="//assets.pinterest.com/js/pinit.js"></script> 

  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=504323752911178";
    fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
  </script>

   <script type="text/javascript">
     $(document).ready(function() {
     $('.five').addClass('active');
     });
   </script


</body>

app/views/preorder/contact.html.erb
    <head>
      <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
        <script type="text/javascript">window.NREUM||(NREUM={});NREUM.info={"beacon":"bam.nr-data.net","errorBeacon":"bam.nr-data.net","licenseKey":"7dbfbf9e37","applicationID":"3521223","transactionName":"c1cIFktXXVldQxxSV11IBwteVkIaUF5eVA==","queueTime":0,"applicationTime":395,"agentToken":null,"agent":"js-agent.newrelic.com/nr-632.min.js"}</script>

        <meta name="viewport" content="width=device-width, initial-scale=1">

    </head>

    <!--[if lt IE 9 ]><body class="lt-ie9"><![endif]-->
    <!--[if (gt IE 9)|!(IE)]><!--> <body><!--<![endif]-->

    <div id="fb-root"></div>
      <script>
        window.fbAsyncInit = function() {
        FB.init({
        appId      : '331145500360318',
        status     : true,
        xfbml      : true
        });
        };

        // Load the SDK asynchronously
        (function(d, s, id){
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) {return;}
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/en_US/all.js";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
      </script>

      <script>
        !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
      </script>
    </div>

    <div id="main">
     <div id="checkout">
      <div id="campaign">
      <%= render 'preorder/nav_stab' %>
        <div id="campaign_body">
      <div class="container clearfix">
        <div class="main_content narrow">
         <div class="tab-content">
                <div class="tab tab-pane fade active in">
                 <% Contact.all.each do |c| %>
                   <%= raw(c.content) %>
                 <% end %> 
                </div>  
              </div>
              </div>
               <%= render 'preorder/reward_sidebar' %>
             </div>
            </div>      


    <%= render 'preorder/foot' %>

  <div class="hide"><a href="https://gwentiana.tilt.com/gwen-tiana-the-debut-album#disqus_thread" data-disqus-identifier="gwen-tiana-the-debut-album" id="parse">0</a></div>
  <script type="text/javascript">
    var disqus_shortname = 'gwentiana';

    (function () {
    var s = document.createElement('script'); s.async = true;
    s.type = 'text/javascript';
    s.src = '//' + disqus_shortname + '.disqus.com/count.js';
    (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());
  </script>
  <script>
    window.onload = function(){

      var parse = document.getElementById('parse');
      var count = document.getElementById('count');

      count.innerHTML=parseInt(parse.innerHTML,10);
    };
  </script>
</div>
    </div>

    <script type="text/javascript" src="//assets.pinterest.com/js/pinit.js"></script> 

  <script type="text/javascript">
     $(document).ready(function() {
     $('.three').addClass('active');
     });
   </script

</body>